WINDOW_WIDTH = 900
WINDOW_HEIGHT = 600

KP = 0.7
KI = 0.1
KD = 0.2
MAX_PID_OUTPUT = 10.0
MIN_PID_OUTPUT = 0.0

START_WATER_LEVEL = 50
TARGET_POOL_LEVEL = 70
MAX_POOL_LEVEL = 100

RESET_INTEGRAL_TO_START = 0

PID_ENABLED = False

MIN_SLIDER = 0
MAX_INFLOW_SLIDER = 10
MAX_OUTFLOW_SLIDER = 9

UPDATE_TIMER_MS = 100

OUTFLOW_RATE = 5

POOL_DEFAULT_LEVEL = 50

WINDOW_TITLE = "HMI Управление бассейном с ПИД-регулятором"
INFLOW_PIPE = "Труба наполнения:"
OUTFLOW_PIPE = "Труба слива:"
PID_CHECKBOX_LABEL = f"Включить ПИД-регулятор (цель: {TARGET_POOL_LEVEL}%)"
RESET_SYSTEM = "Сбросить систему"

# Настройки графика
GRAPH_MINIMUM_HEIGHT = 150
GRAPH_MAX_POINTS = 200
GRAPH_UPDATE_INTERVAL_MS = 200
GRAPH_MARGIN_TOP = 20
GRAPH_MARGIN_BOTTOM = 10
GRAPH_LINE_WIDTH = 2
GRAPH_BG_COLOR = (200, 240, 240)  # RGB
WATER_LINE_COLOR = (0, 0, 200)    # RGB
TARGET_LINE_COLOR = (255, 0, 0)   # RGB

GRAPH_BG_COLOR = (240, 240, 240)    # Цвет фона
WATER_LINE_COLOR = (0, 0, 200)      # Цвет линии графика
TARGET_LINE_COLOR = (255, 0, 0)     # Цвет целевой линии